### ISSUE TITLE
builds of openpyxl=2.4.5 are broken

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/openpyxl-feedstock#1]
See https://bitbucket.org/openpyxl/openpyxl/issues/790/conda-forge-builds-of-openpyxl-245-are (which caused errors in the pandas tests). Apparently some deps are missing.

**Comment by jreback** [comment]
i did look for this recipe  

it's missing jdcal as a dependency
the import tests don't catch this apparently

**Comment by jreback** [comment]
cc @curtisalexander

**Comment by curtisalexander** [comment]
I originally had jdcal included but removed. I will add back.

**Comment by curtisalexander** [comment]
@jreback @jorisvandenbossche Apologies for the broken build. All this is new to me - I added back the dependencies to the meta.yaml file and updated the build number. Do you all know how I can trigger a rebuild of the packages? Do I need to use the `conda-smithy` to re-render the files for the CI services? If so, I won't be able to do so until late Wed. as I am away from home and my development machine (typing this on my phone). Or if one of you want to fork and submotnanPR I will merge.

**Comment by jorisvandenbossche** [comment]
@curtisalexander No problem! 
New builds are triggered automatically when you commit something, and the builds will also be updated on the conda-forge package repo if you increase the build number, which you did. 
You can see here that there are new packages uploaded: https://anaconda.org/conda-forge/openpyxl/files

**Comment by jreback** [comment]
thanks @curtisalexander 

```
(pandas) bash-3.2$ conda create -n test python=3.6 openpyxl -c conda-forge --dry
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/jreback/miniconda3/envs/test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.1.23-0      conda-forge
    certifi:         2017.1.23-py36_0 conda-forge
    et_xmlfile:      1.0.1-py36_0     defaults   
    jdcal:           1.3-py36_0       defaults   
    ncurses:         5.9-10           conda-forge
    openpyxl:        2.4.5-py36_1     conda-forge
    openssl:         1.0.2h-3         conda-forge
    pip:             9.0.1-py36_0     conda-forge
    python:          3.6.1-0          conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      33.1.1-py36_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-1         conda-forge
    wheel:           0.29.0-py36_0    conda-forge
    xz:              5.2.2-0          conda-forge
    zlib:            1.2.11-0         conda-forge
```

you may want to submit recipes for ``jdcal/et_xmlfile``. typically ``conda-forge`` wants to be self-sufficient for all dependencies (even though they may be available on defaults).

**Comment by jreback** [comment]
> you may want to submit recipes for jdcal/et_xmlfile. typically conda-forge wants to be self-sufficient for all dependencies (even though they may be available on defaults).

cc @jakirkham is this accurate?

**Comment by curtisalexander** [comment]
@jakirkham @jreback Ok, I can create builds for both later this week. 

@jorisvandenbossche @jreback Can you all confirm that the inclusion of the dependencies fixes the original issue?

Thanks.

**Comment by jakirkham** [comment]
Yes, that is accurate @jreback, but it is ok to fallback to `defaults` if needed. We just encourage minimal reliance on `defaults`. Would add there are plenty of incentives for packaging things at conda-forge so it doesn't end up being something we have to push to hard.

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche @jreback Can you all confirm that the inclusion of the dependencies fixes the original issue?

Yes it did!

**Comment by jreback** [comment]
thanks!

**Comment by curtisalexander** [comment]
Thanks all.

65a61336bf363706a0153c7743fcaf069f1b33af closes.
